// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: role.proto

package role

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Role) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRoleRequest) Reset() {
	*x = PostRoleRequest{}
	mi := &file_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRoleRequest) ProtoMessage() {}

func (x *PostRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRoleRequest.ProtoReflect.Descriptor instead.
func (*PostRoleRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{1}
}

func (x *PostRoleRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostRoleRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PostRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRoleResponse) Reset() {
	*x = PostRoleResponse{}
	mi := &file_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRoleResponse) ProtoMessage() {}

func (x *PostRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRoleResponse.ProtoReflect.Descriptor instead.
func (*PostRoleResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{2}
}

func (x *PostRoleResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetAllRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRolesRequest) Reset() {
	*x = GetAllRolesRequest{}
	mi := &file_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesRequest) ProtoMessage() {}

func (x *GetAllRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesRequest.ProtoReflect.Descriptor instead.
func (*GetAllRolesRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{3}
}

type GetAllRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllRolesResponse) Reset() {
	*x = GetAllRolesResponse{}
	mi := &file_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllRolesResponse) ProtoMessage() {}

func (x *GetAllRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllRolesResponse.ProtoReflect.Descriptor instead.
func (*GetAllRolesResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{4}
}

func (x *GetAllRolesResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type GetRoleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIDRequest) Reset() {
	*x = GetRoleByIDRequest{}
	mi := &file_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIDRequest) ProtoMessage() {}

func (x *GetRoleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIDRequest.ProtoReflect.Descriptor instead.
func (*GetRoleByIDRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{5}
}

func (x *GetRoleByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRoleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleByIDResponse) Reset() {
	*x = GetRoleByIDResponse{}
	mi := &file_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleByIDResponse) ProtoMessage() {}

func (x *GetRoleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleByIDResponse.ProtoReflect.Descriptor instead.
func (*GetRoleByIDResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{6}
}

func (x *GetRoleByIDResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRolesByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesByUserIDRequest) Reset() {
	*x = GetRolesByUserIDRequest{}
	mi := &file_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesByUserIDRequest) ProtoMessage() {}

func (x *GetRolesByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetRolesByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{7}
}

func (x *GetRolesByUserIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetRolesByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*Role                `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRolesByUserIDResponse) Reset() {
	*x = GetRolesByUserIDResponse{}
	mi := &file_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRolesByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRolesByUserIDResponse) ProtoMessage() {}

func (x *GetRolesByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRolesByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetRolesByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{8}
}

func (x *GetRolesByUserIDResponse) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

type PatchRoleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRoleByIDRequest) Reset() {
	*x = PatchRoleByIDRequest{}
	mi := &file_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRoleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoleByIDRequest) ProtoMessage() {}

func (x *PatchRoleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoleByIDRequest.ProtoReflect.Descriptor instead.
func (*PatchRoleByIDRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{9}
}

func (x *PatchRoleByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchRoleByIDRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PatchRoleByIDRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchRoleByIDRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type PatchRoleByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *Role                  `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRoleByIDResponse) Reset() {
	*x = PatchRoleByIDResponse{}
	mi := &file_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRoleByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoleByIDResponse) ProtoMessage() {}

func (x *PatchRoleByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoleByIDResponse.ProtoReflect.Descriptor instead.
func (*PatchRoleByIDResponse) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{10}
}

func (x *PatchRoleByIDResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleByIDRequest) Reset() {
	*x = DeleteRoleByIDRequest{}
	mi := &file_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleByIDRequest) ProtoMessage() {}

func (x *DeleteRoleByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleByIDRequest) Descriptor() ([]byte, []int) {
	return file_role_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRoleByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_role_proto protoreflect.FileDescriptor

const file_role_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"role.proto\x12\x04role\x1a\x1bgoogle/protobuf/empty.proto\"e\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"`\n" +
	"\x0fPostRoleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"2\n" +
	"\x10PostRoleResponse\x12\x1e\n" +
	"\x04role\x18\x01 \x01(\v2\n" +
	".role.RoleR\x04role\"\x14\n" +
	"\x12GetAllRolesRequest\"7\n" +
	"\x13GetAllRolesResponse\x12 \n" +
	"\x05roles\x18\x01 \x03(\v2\n" +
	".role.RoleR\x05roles\"$\n" +
	"\x12GetRoleByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x13GetRoleByIDResponse\x12\x1e\n" +
	"\x04role\x18\x01 \x01(\v2\n" +
	".role.RoleR\x04role\"2\n" +
	"\x17GetRolesByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"<\n" +
	"\x18GetRolesByUserIDResponse\x12 \n" +
	"\x05roles\x18\x01 \x03(\v2\n" +
	".role.RoleR\x05roles\"u\n" +
	"\x14PatchRoleByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"7\n" +
	"\x15PatchRoleByIDResponse\x12\x1e\n" +
	"\x04role\x18\x01 \x01(\v2\n" +
	".role.RoleR\x04role\"'\n" +
	"\x15DeleteRoleByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xb4\x03\n" +
	"\vRoleService\x129\n" +
	"\bPostRole\x12\x15.role.PostRoleRequest\x1a\x16.role.PostRoleResponse\x12B\n" +
	"\vGetAllRoles\x12\x18.role.GetAllRolesRequest\x1a\x19.role.GetAllRolesResponse\x12B\n" +
	"\vGetRoleByID\x12\x18.role.GetRoleByIDRequest\x1a\x19.role.GetRoleByIDResponse\x12Q\n" +
	"\x10GetRolesByUserID\x12\x1d.role.GetRolesByUserIDRequest\x1a\x1e.role.GetRolesByUserIDResponse\x12H\n" +
	"\rPatchRoleByID\x12\x1a.role.PatchRoleByIDRequest\x1a\x1b.role.PatchRoleByIDResponse\x12E\n" +
	"\x0eDeleteRoleByID\x12\x1b.role.DeleteRoleByIDRequest\x1a\x16.google.protobuf.EmptyB%Z#myproject/project-protos/proto/roleb\x06proto3"

var (
	file_role_proto_rawDescOnce sync.Once
	file_role_proto_rawDescData []byte
)

func file_role_proto_rawDescGZIP() []byte {
	file_role_proto_rawDescOnce.Do(func() {
		file_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)))
	})
	return file_role_proto_rawDescData
}

var file_role_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_role_proto_goTypes = []any{
	(*Role)(nil),                     // 0: role.Role
	(*PostRoleRequest)(nil),          // 1: role.PostRoleRequest
	(*PostRoleResponse)(nil),         // 2: role.PostRoleResponse
	(*GetAllRolesRequest)(nil),       // 3: role.GetAllRolesRequest
	(*GetAllRolesResponse)(nil),      // 4: role.GetAllRolesResponse
	(*GetRoleByIDRequest)(nil),       // 5: role.GetRoleByIDRequest
	(*GetRoleByIDResponse)(nil),      // 6: role.GetRoleByIDResponse
	(*GetRolesByUserIDRequest)(nil),  // 7: role.GetRolesByUserIDRequest
	(*GetRolesByUserIDResponse)(nil), // 8: role.GetRolesByUserIDResponse
	(*PatchRoleByIDRequest)(nil),     // 9: role.PatchRoleByIDRequest
	(*PatchRoleByIDResponse)(nil),    // 10: role.PatchRoleByIDResponse
	(*DeleteRoleByIDRequest)(nil),    // 11: role.DeleteRoleByIDRequest
	(*emptypb.Empty)(nil),            // 12: google.protobuf.Empty
}
var file_role_proto_depIdxs = []int32{
	0,  // 0: role.PostRoleResponse.role:type_name -> role.Role
	0,  // 1: role.GetAllRolesResponse.roles:type_name -> role.Role
	0,  // 2: role.GetRoleByIDResponse.role:type_name -> role.Role
	0,  // 3: role.GetRolesByUserIDResponse.roles:type_name -> role.Role
	0,  // 4: role.PatchRoleByIDResponse.role:type_name -> role.Role
	1,  // 5: role.RoleService.PostRole:input_type -> role.PostRoleRequest
	3,  // 6: role.RoleService.GetAllRoles:input_type -> role.GetAllRolesRequest
	5,  // 7: role.RoleService.GetRoleByID:input_type -> role.GetRoleByIDRequest
	7,  // 8: role.RoleService.GetRolesByUserID:input_type -> role.GetRolesByUserIDRequest
	9,  // 9: role.RoleService.PatchRoleByID:input_type -> role.PatchRoleByIDRequest
	11, // 10: role.RoleService.DeleteRoleByID:input_type -> role.DeleteRoleByIDRequest
	2,  // 11: role.RoleService.PostRole:output_type -> role.PostRoleResponse
	4,  // 12: role.RoleService.GetAllRoles:output_type -> role.GetAllRolesResponse
	6,  // 13: role.RoleService.GetRoleByID:output_type -> role.GetRoleByIDResponse
	8,  // 14: role.RoleService.GetRolesByUserID:output_type -> role.GetRolesByUserIDResponse
	10, // 15: role.RoleService.PatchRoleByID:output_type -> role.PatchRoleByIDResponse
	12, // 16: role.RoleService.DeleteRoleByID:output_type -> google.protobuf.Empty
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_role_proto_init() }
func file_role_proto_init() {
	if File_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_role_proto_rawDesc), len(file_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_role_proto_goTypes,
		DependencyIndexes: file_role_proto_depIdxs,
		MessageInfos:      file_role_proto_msgTypes,
	}.Build()
	File_role_proto = out.File
	file_role_proto_goTypes = nil
	file_role_proto_depIdxs = nil
}
