// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TasksStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Total             int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Completed         int64                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Pending           int64                  `protobuf:"varint,3,opt,name=pending,proto3" json:"pending,omitempty"`
	CompletionPercent float64                `protobuf:"fixed64,4,opt,name=completion_percent,json=completionPercent,proto3" json:"completion_percent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TasksStatisticsResponse) Reset() {
	*x = TasksStatisticsResponse{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksStatisticsResponse) ProtoMessage() {}

func (x *TasksStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksStatisticsResponse.ProtoReflect.Descriptor instead.
func (*TasksStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *TasksStatisticsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TasksStatisticsResponse) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *TasksStatisticsResponse) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *TasksStatisticsResponse) GetCompletionPercent() float64 {
	if x != nil {
		return x.CompletionPercent
	}
	return 0
}

type ActiveUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	TasksCount    int64                  `protobuf:"varint,3,opt,name=tasks_count,json=tasksCount,proto3" json:"tasks_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActiveUser) Reset() {
	*x = ActiveUser{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveUser) ProtoMessage() {}

func (x *ActiveUser) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveUser.ProtoReflect.Descriptor instead.
func (*ActiveUser) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *ActiveUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ActiveUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ActiveUser) GetTasksCount() int64 {
	if x != nil {
		return x.TasksCount
	}
	return 0
}

type TopActiveUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ActiveUser          `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopActiveUsersResponse) Reset() {
	*x = TopActiveUsersResponse{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopActiveUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopActiveUsersResponse) ProtoMessage() {}

func (x *TopActiveUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopActiveUsersResponse.ProtoReflect.Descriptor instead.
func (*TopActiveUsersResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TopActiveUsersResponse) GetUsers() []*ActiveUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type HourActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hour          int32                  `protobuf:"varint,1,opt,name=hour,proto3" json:"hour,omitempty"`
	TasksCount    int64                  `protobuf:"varint,2,opt,name=tasks_count,json=tasksCount,proto3" json:"tasks_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HourActivity) Reset() {
	*x = HourActivity{}
	mi := &file_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HourActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HourActivity) ProtoMessage() {}

func (x *HourActivity) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HourActivity.ProtoReflect.Descriptor instead.
func (*HourActivity) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *HourActivity) GetHour() int32 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *HourActivity) GetTasksCount() int64 {
	if x != nil {
		return x.TasksCount
	}
	return 0
}

type TasksHourlyActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activity      []*HourActivity        `protobuf:"bytes,1,rep,name=activity,proto3" json:"activity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TasksHourlyActivityResponse) Reset() {
	*x = TasksHourlyActivityResponse{}
	mi := &file_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TasksHourlyActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TasksHourlyActivityResponse) ProtoMessage() {}

func (x *TasksHourlyActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TasksHourlyActivityResponse.ProtoReflect.Descriptor instead.
func (*TasksHourlyActivityResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TasksHourlyActivityResponse) GetActivity() []*HourActivity {
	if x != nil {
		return x.Activity
	}
	return nil
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1bgoogle/protobuf/empty.proto\"\x96\x01\n" +
	"\x17TasksStatisticsResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x03R\tcompleted\x12\x18\n" +
	"\apending\x18\x03 \x01(\x03R\apending\x12-\n" +
	"\x12completion_percent\x18\x04 \x01(\x01R\x11completionPercent\"\\\n" +
	"\n" +
	"ActiveUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1f\n" +
	"\vtasks_count\x18\x03 \x01(\x03R\n" +
	"tasksCount\"E\n" +
	"\x16TopActiveUsersResponse\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.analytics.ActiveUserR\x05users\"C\n" +
	"\fHourActivity\x12\x12\n" +
	"\x04hour\x18\x01 \x01(\x05R\x04hour\x12\x1f\n" +
	"\vtasks_count\x18\x02 \x01(\x03R\n" +
	"tasksCount\"R\n" +
	"\x1bTasksHourlyActivityResponse\x123\n" +
	"\bactivity\x18\x01 \x03(\v2\x17.analytics.HourActivityR\bactivity2\x8e\x02\n" +
	"\x10AnalyticsService\x12P\n" +
	"\x12GetTasksStatistics\x12\x16.google.protobuf.Empty\x1a\".analytics.TasksStatisticsResponse\x12N\n" +
	"\x11GetTopActiveUsers\x12\x16.google.protobuf.Empty\x1a!.analytics.TopActiveUsersResponse\x12X\n" +
	"\x16GetTasksHourlyActivity\x12\x16.google.protobuf.Empty\x1a&.analytics.TasksHourlyActivityResponseB*Z(myproject/project-protos/proto/analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_analytics_proto_goTypes = []any{
	(*TasksStatisticsResponse)(nil),     // 0: analytics.TasksStatisticsResponse
	(*ActiveUser)(nil),                  // 1: analytics.ActiveUser
	(*TopActiveUsersResponse)(nil),      // 2: analytics.TopActiveUsersResponse
	(*HourActivity)(nil),                // 3: analytics.HourActivity
	(*TasksHourlyActivityResponse)(nil), // 4: analytics.TasksHourlyActivityResponse
	(*emptypb.Empty)(nil),               // 5: google.protobuf.Empty
}
var file_analytics_proto_depIdxs = []int32{
	1, // 0: analytics.TopActiveUsersResponse.users:type_name -> analytics.ActiveUser
	3, // 1: analytics.TasksHourlyActivityResponse.activity:type_name -> analytics.HourActivity
	5, // 2: analytics.AnalyticsService.GetTasksStatistics:input_type -> google.protobuf.Empty
	5, // 3: analytics.AnalyticsService.GetTopActiveUsers:input_type -> google.protobuf.Empty
	5, // 4: analytics.AnalyticsService.GetTasksHourlyActivity:input_type -> google.protobuf.Empty
	0, // 5: analytics.AnalyticsService.GetTasksStatistics:output_type -> analytics.TasksStatisticsResponse
	2, // 6: analytics.AnalyticsService.GetTopActiveUsers:output_type -> analytics.TopActiveUsersResponse
	4, // 7: analytics.AnalyticsService.GetTasksHourlyActivity:output_type -> analytics.TasksHourlyActivityResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
