// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetTasksStatistics_FullMethodName     = "/analytics.AnalyticsService/GetTasksStatistics"
	AnalyticsService_GetTopActiveUsers_FullMethodName      = "/analytics.AnalyticsService/GetTopActiveUsers"
	AnalyticsService_GetTasksHourlyActivity_FullMethodName = "/analytics.AnalyticsService/GetTasksHourlyActivity"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	GetTasksStatistics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksStatisticsResponse, error)
	GetTopActiveUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TopActiveUsersResponse, error)
	GetTasksHourlyActivity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksHourlyActivityResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetTasksStatistics(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksStatisticsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTasksStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTopActiveUsers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TopActiveUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TopActiveUsersResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTopActiveUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTasksHourlyActivity(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TasksHourlyActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TasksHourlyActivityResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTasksHourlyActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
type AnalyticsServiceServer interface {
	GetTasksStatistics(context.Context, *emptypb.Empty) (*TasksStatisticsResponse, error)
	GetTopActiveUsers(context.Context, *emptypb.Empty) (*TopActiveUsersResponse, error)
	GetTasksHourlyActivity(context.Context, *emptypb.Empty) (*TasksHourlyActivityResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetTasksStatistics(context.Context, *emptypb.Empty) (*TasksStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksStatistics not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTopActiveUsers(context.Context, *emptypb.Empty) (*TopActiveUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopActiveUsers not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTasksHourlyActivity(context.Context, *emptypb.Empty) (*TasksHourlyActivityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTasksHourlyActivity not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetTasksStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTasksStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTasksStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTasksStatistics(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTopActiveUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTopActiveUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTopActiveUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTopActiveUsers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTasksHourlyActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTasksHourlyActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTasksHourlyActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTasksHourlyActivity(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTasksStatistics",
			Handler:    _AnalyticsService_GetTasksStatistics_Handler,
		},
		{
			MethodName: "GetTopActiveUsers",
			Handler:    _AnalyticsService_GetTopActiveUsers_Handler,
		},
		{
			MethodName: "GetTasksHourlyActivity",
			Handler:    _AnalyticsService_GetTasksHourlyActivity_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
